### ISSUE TITLE
Erro na linha 8

### ISSUE THREAD

**Issue by jaisonv** [phoemur/fundamentus#1]
Tentei rodar aqui e recebi um erro nessa linha:

from lxml.html import fragment_fromstring

Ele diz que não foi possivel encontrar o 'fragment_fromstring'.

Sabe o que pode ser isso?

**Comment by phoemur** [comment]
Tem que instalar o lxml pra funcionar.
python3 -m pip install lxml

Se quiser que funcione o server.py terá que instalar as dependências do
Flask também. Os módulos necessários estão listados no arquivo required.txt

Em 08/09/2016 15:33, "Jaison D. Vieira" notifications@github.com escreveu:

**Comment by jaisonv** [comment]
Funcionou. Obrigado!
