### ISSUE TITLE
 WARNING: This is a development server. Do not use it in a production deployment.

### ISSUE THREAD

**Issue by Guillerbr** [phoemur/fundamentus#11]
Estou tentado rodar a API em produção.
Esse aviso diz para não usar em produção...
Qual motivo?
É possível usar em produção?

Att

**Comment by phoemur** [comment]
O motivo é que o servidor do Flask é somente para debug.
Para produção você pode rodar em nginx, ou até mesmo gunicorn...
Tem muitas opções disponíveis
