### ISSUE TITLE
Projeto em node.js

### ISSUE THREAD

**Issue by sebrax** [phoemur/fundamentus#12]
Olá, pessoal, baseado nesse projeto, criei a aplicação em nodejs utilizando o [osmosis ](https://www.npmjs.com/package/osmosis) para obter os dados e gero em json.

Só desenvolvi outro por 3 motivos:
1. Existem mais dados dentro da página do ativo e já consegui entrar e obter os mesmos.
2. A Fundamentus guarda ativos que já não existem mais e também tem dados nulos, logo faz-se necessário tirar os mesmos do arquivo final.
3. Não desenvolvo em Python (ainda rs).

Incluí também a função de gerar json somente com ativos que publicaram resultado do trimestre atual.

Tenho o código pronto e funcional mas fiz há algum tempo e o mesmo está meio bagunçado e estou sem tempo de aprimorar e criar a API, então se alguém animar, publico aqui e podemos dar continuidade.

Exemplo de json gerado do 4 trimestre de 2019:
`{
        "papel": "MGLU3",
        "tipo": "ON NM",
        "cotacao": "41,65",
        "ult_cotacao": "09/04/2020",
        "vol_med_2m": "789.875.000",
        "ult_balanco": "31/12/2019",
        "qtd_acoes": "1.624.730.000",
        "p_l": "73,41",
        "p_vp": "8,95",
        "p_ebit": "73,45",
        "psr": "3,40",
        "p_ativos": "3,42",
        "p_capGiro": "13,99",
        "p_ativCircLiq": "110,03",
        "divYield": "0,4%",
        "ev_ebit": "45,28",
        "giro_ativos": "69,21",
        "cresc_rec_5a": "23,2%",
        "lpa": "0,57",
        "vpa": "4,66",
        "margem_bruta": "27,9%",
        "margemEbit": "4,6%",
        "margem_liquida": "4,6%",
        "ebit_ativo": "4,7%",
        "roic": "10,1%",
        "roe": "12,2%",
        "liquidez_corr": "1,60",
        "div_brut_patri": "0,11",
        "ativo": "19.791.100.000",
        "disponibilidades": "4.753.900.000",
        "ativo_circulante": "12.841.200.000",
        "div_bruta": "848.829.000",
        "div_liquida": "-3.905.080.000",
        "patrim_liq": "7.564.940.000",
        "receita_liq_12m": "19.886.300.000",
        "ebit_12m": "921.287.000",
        "luc_liq_12m": "921.828.000",
        "receita_liq_3m": "6.385.030.000",
        "ebit_3m": "364.753.000",
        "luc_liq_3m": "167.998.000",
        "setor": "Comércio"
    }`

**Comment by pedroddomingues** [comment]
Joga o código no seu github, quem tiver interesse e tempo vai te ajudar a melhorá-lo. 

Eu tenho interesse mas não tenho tempo :(

Se puder postar eu já agradeço, um amigo está pegando esses dados na mão de vários papéis, eu usaria para criar uma tabela dos que ele quer comparar, por exemplo
