### ISSUE TITLE
Usar em modo de producao

### ISSUE THREAD

**Issue by Guillerbr** [phoemur/fundamentus#6]
Tentei subir em um servidor web na nuvem e tive algumas dificuldades.
O aplicativo pode ser usado somente em modo local de desenvolvimento?

**Comment by phoemur** [comment]
Não, você pode usar do jeito que você quiser.
Como é um microservice feito em Flask, você deve estudar as formas de deployment de aplicações flask.
Tem muitas opções, usando nginx, apache, uwsgi ou subindo a aplicação para servidor da nuvem.
Não tem receita de bolo.

veja:
https://flask.palletsprojects.com/en/1.1.x/deploying/

**Comment by phoemur** [comment]
Como não tem relação com meu script  e sim com o Framework Flask, fechei essa questão

**Comment by Guillerbr** [comment]
Subi na AWS e não funcionou,não podemos criar uma pasta de DOC,ensinando a subir a aplicação na nuvem ou servidores remotos.O que acha?
